pipeline {
  agent {
        node {
            label 'v2_builder'
        }
    }
    stages {
      stage ('Clean npm-dev artifactory repo') {
        steps {
          echo 'Calling script'
            withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'c376347e-4245-49fc-be2c-b4aa0ddce81f',usernameVariable: 'NAME', passwordVariable: 'WORD']]) {
              sh "python REL-11257/npm-dev-cleaner.py -v -u ${NAME} -p ${WORD}"
            }
         }
      }
   }
}
